- name: create user
  user:
    name: famigraph
    comment: "Famigraph User (for running famigraph.xyz)"
    shell: /sbin/nologin
    state: present
    create_home: no
    system: yes

- name: create directories
  file:
      path: "{{ item }}"
      state: directory
      owner: famigraph
      group: famigraph
  with_items:
  - "/opt/famigraph/"
  - "/opt/famigraph/crt"
  - "/opt/famigraph/bin"
  - "/var/lib/famigraph/"

- name: copy needed files
  template:
      src: ".{{ item }}.j2"
      dest: "{{ item }}"
      owner: famigraph
      group: famigraph
  with_items:
  - "/opt/famigraph/config.json"
  - "/opt/famigraph/crt/certificate.crt"
  - "/opt/famigraph/crt/private.key"
  - "/etc/systemd/system/famigraph.service"

- name: copy binary
  copy:
      src: "../../../build/famigraph-amd64"
      dest: "/opt/famigraph/bin/famigraph"
      mode: 0755
      owner: famigraph
      group: famigraph

- name: Allow binary to bind port 443
  shell: sudo setcap 'cap_net_bind_service=+ep' /opt/famigraph/bin/famigraph

- name: systemd daemon_reload
  systemd:
      daemon_reload: true

- name: enable and restart famigraph
  systemd:
      name: famigraph
      enabled: true
      state: restarted

- name: fetch cloudflare v4 ips
  uri:
      url: https://www.cloudflare.com/ips-v4/#
      return_content: yes
  register: cloudflare_ipv4_ips


- name: fetch cloudflare v6 ips
  uri:
      url: https://www.cloudflare.com/ips-v6/#
      return_content: yes
  register: cloudflare_ipv6_ips

- name: flush old firewall rules
  ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
      delete: true
  with_items:
    - "80"
    - "443"

- name: open firewall port 80
  ufw:
      rule: allow
      port: 80
      proto: tcp
      from_ip: "{{ item }}"
  with_items:
  - "{{ cloudflare_ipv4_ips.content.splitlines() }}"
  - "{{ cloudflare_ipv6_ips.content.splitlines() }}"

- name: open firewall port 443
  ufw:
      rule: allow
      port: 443
      proto: tcp
      from_ip: "{{ item }}"
  with_items:
  - "{{ cloudflare_ipv4_ips.content.splitlines() }}"
  - "{{ cloudflare_ipv6_ips.content.splitlines() }}"
